services:
  vackup-docker-extension:
    image: ${DESKTOP_PLUGIN_IMAGE}
    restart: unless-stopped
    cap_add:
      - DAC_OVERRIDE
      - FOWNER
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
