name: Run Benchmarks

on:
  push:
    branches:
      - main
    paths:
      - '**.go'
      - 'go.*'
      - '.github/**'
  pull_request:
    branches:
      - main
    paths:
      - '**.go'
      - 'go.*'
      - '.github/**'
  workflow_dispatch:

jobs:
  benchmark:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: [1.17]
    name: Benchmark comparison ${{ matrix.os }} @ Go ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code (Previous)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
          path: previous

      - name: Checkout Code (New)
        uses: actions/checkout@v3
        with:
          path: new

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Install Dependencies
        run: go install golang.org/x/perf/cmd/benchstat@latest

      - name: Run Benchmark (Previous)
        run: |
          cd previous/vm
          go test -timeout 30m -run="-" -bench=".*" -count=1 ./... | tee benchmark.txt

      - name: Run Benchmark (New)
        run: |
          cd new/vm
          go test -timeout 30m -run="-" -bench=".*" -count=1 ./... | tee benchmark.txt

      - name: Run Benchstat (Previous vs New)
        run: |
          benchstat previous/vm/benchmark.txt new/vm/benchmark.txt

      - name: Run Benchstat (New)
        run: |
          benchstat new/vm/benchmark.txt